apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config # Tên của ConfigMap
data:
  WORDPRESS_DB_HOST: mysql # Địa chỉ host của MySQL
  WORDPRESS_DB_NAME: wordpress # Cơ sở dữ liệu WordPress
  WORDPRESS_DB_USER: wpuser # Tên người dùng WordPress
